-- MySQL Script generated by MySQL Workbench
-- Wed Jun  2 16:36:25 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Usuarios` (
  `UsuarioId` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `Usuario` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UsuarioId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FotoPerfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FotoPerfil` (
  `FotoId` INT NOT NULL AUTO_INCREMENT,
  `FotoPath` VARCHAR(45) NOT NULL,
  `UsuarioId` INT NOT NULL,
  PRIMARY KEY (`FotoId`),
  INDEX `fk_FotoPerfil_Usuarios_idx` (`UsuarioId` ASC) ,
  CONSTRAINT `fk_FotoPerfil_Usuarios`
    FOREIGN KEY (`UsuarioId`)
    REFERENCES `Usuarios` (`UsuarioId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
